name: CI

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [8, 11, 17, 21]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - name: Setup and execute Gradle 'counter:jmh' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: counter:jmh
    - name: Upload the result of 'counter:jmh' task
      uses: actions/upload-artifact@v4
      with:
        name: java-${{ matrix.java_version }}-counter-result-csv
        path: counter/build/results/jmh/results.csv
    - name: Setup and execute Gradle 'map:jmh' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: map:jmh
    - name: Upload the result of 'map:jmh' task
      uses: actions/upload-artifact@v4
      with:
        name: java-${{ matrix.java_version }}-map-result-csv
        path: map/build/results/jmh/results.csv


